### ISSUE TITLE
Passing multiple props based on route; not just `children`

### ISSUE THREAD

**Issue by mhelvens** [KidkArolis/space-router#17]
From what I understand, space-router passes child-route components as the `children` prop to the parent route component. It would be useful if we had the option of passing multiple props based on route configuration. One for rendering the main page, say, and one for rendering some controls in the upper right corner.

I'm imagining a syntax like this, though I suspect it wouldn't be compatible with the current API:

```javascript
const routes = ['', Qfn, [
  ['/p/:propertyId/integrations/:friendlyId', {
    mainPage: QfnOverview,
    controls: QfnOverviewControls
  }],
  // other stuff
]]
```

**Comment by KidkArolis** [comment]
Space router is actually not react specific and is in fact agnostic to what you put into the route data.

For example all of these are valid:

```js
["/p/:propertyId"]
["/p/:propertyId", 1]
["/p/:propertyId", "abc"]
["/p/:propertyId", require('Component')]
["/p/:propertyId", { a: 1, b: 2, c: 3 }],
["/p/:propertyId", { mainPage, controls }]
```

You can then do whatever with this route data when the route matches, e.g.:

```
// option 1
router.start((router, data) => { render(data.mainPage) })

// option 2
router.start((router) => atom.dispatch('navigated', route))
render(router.data(atom.get().route.pattern).mainPage)
```

I think in your case you might be using `shallot`, to which I can no longer have access. But this decision about how to handle the data would have to be done there, it's probably similar to this:

https://github.com/KidkArolis/moonwave/blob/master/react.js#L22

You could imagine doing a few things there. One idea would to set the component and extra context, e.g.:

```
['/p/:propertyId/integrations/:friendlyId', {
    Component: QfnOverview,
    context: { controls: QfnOverviewControls }
  }]
```

This way, `shallot` would still render Component, but you could add extra logic to also pass the extra context via `<Provider/>` and then reach for that anywhere in your tree.

I hope this makes sense.

**Comment by mhelvens** [comment]
Ah, I see, it's `shallot`. Sorry! I should have done my homework before asking here. Yes, it does make sense.

Hope you're doing well?
